version: '2.3'

x-rnode:
  &default-rnode
  image: rchain/rnode:v0.13.0-alpha
  user: root

########################################################################
services:
########################################################################

  node3:
    << : *default-rnode
    container_name: node3
    ports:
      - 40430:40430
      - 40432:40402
      - 40434:40434
    volumes:
      - $RNODE_DIR/node3/rnode/:/var/lib/rnode/
    command:
      $RNODE_JAVA_CONFIG
      $RNODE_RUN_CONFIG      --api-max-blocks-limit=3  
      --host node3.$DOMAIN   --protocol-port 40430 --discovery-port 40434

########################################################################
  node4:
    << : *default-rnode
    container_name: node4
    ports:
      - 40440:40440
      - 40442:40402
      - 40444:40444
    volumes:
      - $RNODE_DIR/node4/rnode/:/var/lib/rnode/
    command:
      $RNODE_JAVA_CONFIG
      $RNODE_RUN_CONFIG      --api-max-blocks-limit=3
      --host node4.$DOMAIN   --protocol-port 40440 --discovery-port 40444

########################################################################
  observer2:
    << : *default-rnode
    container_name: observer2
    ports:
      - 40450:40450
      - 40454:40454
    volumes:
      - $RNODE_DIR/observer2/rnode/:/var/lib/rnode/
    command:
      $RNODE_JAVA_CONFIG
      $RNODE_RUN_CONFIG         --api-max-blocks-limit=100 --api-enable-reporting
      --host observer2.$DOMAIN   --protocol-port 40450 --discovery-port 40454

########################################################################
  transaction-server:
    image: zsluedem/transaction-server:0.1.8
    container_name: transaction-server
    user: root
    ports:
      - 7070:7070
    volumes:
      - $RNODE_DIR/transaction-server/transactionsDB:/transaction_server/transactionsDB
      - $RNODE_DIR/transaction-server/transaction.yml:/transaction_server/config.yml
      - $RNODE_DIR/transaction-server/transactions.log:/var/log/transactions.log

########################################################################
#  revdefine-init-rnode:
#    image: zsluedem/revdefine:revdefine-0.2.0-alpha
#    user: root
#    container_name: revdefine-init-rnode
#    environment:
#      - MONGO_URI=mongodb://mongod:27017   # use the mongo container name as host name and the mongo container needs to be up
#    entrypoint: /opt/docker/bin/init
#    command:
#      [
#          "--data-dir",
#          "/var/lib/rnode",
#          "--genesis-block-hash",
#          "96864cccb203b643ea994e2114379b7fb2c2555e922f92338e4b0681e02ba09c",
#          "--genesis-wallet-file",
#          "/var/lib/wallets.txt",
#          "--genesis-bonds-file",
#          "/var/lib/bonds.txt",
#      ]
#    volumes:
#      - $RNODE_DIR/revdefine/rnode:/var/lib/rnode
#      - $RNODE_DIR/node0/rnode/genesis/bonds.txt:/var/lib/bonds.txt
#      - $RNODE_DIR/node0/rnode/genesis/wallets.txt:/var/lib/wallets.txt
########################################################################
  revdefine-rnode:
    image: zsluedem/revdefine:revdefine-0.2.0-alpha
    #image: rchain/rnode:v0.13.0-alpha
    user: root
    container_name: revdefine-rnode
    environment:
      - MONGO_URI=mongodb://mongod:27017   # use the mongo container name as host name 
    ports:
      - "40460:40460"
      - "40464:40464"
        #      - "40466:40406"  # revdefine use 40406 port
    command:
      $RNODE_JAVA_CONFIG
      $RNODE_RUN_CONFIG         --api-enable-reporting
      --host revdefine-rnode.$DOMAIN   --protocol-port 40460 --discovery-port 40464
    volumes:
      - $RNODE_DIR/revdefine/rnode/:/var/lib/rnode/

########################################################################
  mongod:
    image: mongo
    user: root
    container_name: mongod  # mongo host name in docker network
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - $RNODE_DIR/revdefine/mongod:/data/db  # mongDB db file
      - $RNODE_DIR/revdefine/mongod.conf:/etc/mongo/mongod.conf  # mongoDB configuration
    command:
      [ "--config", "/etc/mongo/mongod.conf" ]

########################################################################
  revproxy:
    image: nginx
    container_name: revproxy
    ports:
      - 443:443
      - 40401:40401
    volumes:
      - $RNODE_DIR/revproxy/conf:/etc/nginx/conf.d:ro
      - $RNODE_DIR/files/letsencrypt:/etc/letsencrypt:ro
      - $RNODE_DIR/revproxy/log:/var/log/nginx
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

########################################################################
  logspout:
    image: gliderlabs/logspout
    container_name: logspout
    ports:
      - 8181:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

